rootProject.name = "Adyeshach"

include("plugin")
include("project:common")
include("project:common-impl")
include("project:common-impl-nms")
include("project:common-impl-nms19")
include("project:common-impl-nms21")
include("project:common-impl-nms19p")
include("project:common-impl-nms20p")
include("project:module-bukkit")
include("project:compat-beton-quest")
include("project:compat-germ-engine")
include("project:compat-model-engine-v2")
include("project:compat-model-engine-v4")
include("project:module-editor")
include("project:module-language")
include("project:module-legacy-api")
